@host = http://127.0.0.1:6000/v1/cats

GET {{host}}/?fields=name&offset=0&limit=2&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzMDEwMzE4fQ.bOs0LTv4E4YXm5zAXzhcCT5m7Askj7EmuWxkJHxLyWc HTTP/1.1


###
POST {{host}}/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOjEwMCwiZXhwIjoxNjUzMDEwMzE4fQ.bOs0LTv4E4YXm5zAXzhcCT5m7Askj7EmuWxkJHxLyWc HTTP/1.1
Content-Type: application/json

{
    "id": 1,
    "name": "Iring 2"
}


###
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 19,
    "name": "Iring"
}


###
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[21,23,12,16,17]



### Get single cat
GET {{host}}/1?fields=id HTTP/1.1


###
PUT {{host}}/22 HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "name": "Miming"
}


###
DELETE {{host}}/22 HTTP/1.1
